# Generated by Django 3.1.1 on 2020-11-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField()),
                ('alert_type', models.CharField(max_length=64)),
                ('alert_desc', models.CharField(max_length=256)),
                ('alert_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='db_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
                ('max_power', models.DecimalField(decimal_places=3, max_digits=10)),
                ('day_perc', models.DecimalField(decimal_places=5, max_digits=10)),
                ('night_perc', models.DecimalField(decimal_places=5, max_digits=10)),
                ('yellow_perc', models.DecimalField(decimal_places=5, max_digits=10)),
                ('red_perc', models.DecimalField(decimal_places=5, max_digits=10)),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='db_opt_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=256)),
                ('group_name', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('energy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='db_ui_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=256)),
                ('group_name', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('energy', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='db_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('session_id', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recent_station_id', models.CharField(blank=True, max_length=256)),
                ('recent_port_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='db_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=128)),
                ('group_name', models.CharField(max_length=256)),
                ('station_load', models.DecimalField(decimal_places=3, max_digits=10)),
                ('port_number', models.CharField(max_length=10)),
                ('port_status', models.CharField(max_length=64)),
                ('shed_state', models.BooleanField()),
                ('port_load', models.DecimalField(decimal_places=3, max_digits=10)),
                ('allowed_load', models.DecimalField(decimal_places=3, max_digits=10)),
                ('port_power', models.DecimalField(decimal_places=3, max_digits=10)),
                ('port_timestamp', models.DateTimeField()),
                ('exception_flag', models.BooleanField(default=False)),
                ('recent_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devine.db_user')),
            ],
            options={
                'unique_together': {('station_id', 'port_number')},
            },
        ),
    ]
