# Generated by Django 3.1.1 on 2020-11-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_opt_session',
            name='user_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='db_ui_session',
            name='user_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
