# Generated by Django 3.1.1 on 2020-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devine', '0003_auto_20201110_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_user',
            name='group_name',
            field=models.CharField(default='slac_GISMO', max_length=256),
        ),
    ]
