# Generated by Django 3.1.1 on 2020-12-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devine', '0004_db_user_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('yellow_load', models.BooleanField(default=False)),
                ('red_load', models.BooleanField(default=False)),
                ('telecomm_alert', models.BooleanField(default=False)),
            ],
        ),
    ]
