# Generated by Django 3.1.1 on 2020-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devine', '0005_db_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_alert',
            name='group_name',
            field=models.CharField(default='slac_GISMO', max_length=256),
        ),
        migrations.AddField(
            model_name='db_notification',
            name='group_name',
            field=models.CharField(default='slac_GISMO', max_length=256),
        ),
    ]
